version: '3'
services:
  #  bricoll_nginx:
  #    image: nginx
  #    volumes:
  #      - ./nginx/nginx.conf:/tmp/nginx.conf
  #    environment:
  #      - NEXTJS_SERVER_ADDR=bricoll_nextjs:3000
  #    command: /bin/bash -c "envsubst < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf && nginx -g 'daemon off;';"
  #    ports:
  #      - "80:80"
  #    depends_on:
  #      - bricoll_nextjs
  #    restart: on-failure
  #    hostname: bricoll_nginx
  #    container_name: bricoll_nginx
  bricoll_nextjs:
    image: nextjs
    build: ./nextjs
    ports:
      - "3000:3000"

    restart: always
    env_file:
      - ./nextjs/.env.local

    depends_on:
      - bricoll_mongo
    hostname: bricoll_nextjs
    container_name: bricoll_nextjs
  bricoll_mongo:
    image: mongo
    volumes:
      - /data/db
    hostname: bricoll_mongo
    container_name: bricoll_mongo
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=bricoll
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_PASSWORD} # set in .env (set your own)
    restart: always
  bricoll_redis:
    image: redis
    restart: always
    hostname: bricoll_redis
    container_name: bricoll_redis
    volumes:
      - /data


#  portainer:
#    image: portainer/portainer-ce:latest
#    ports:
#      - "9443:9443"
#    volumes:
#      - data:/data
#      - /var/run/docker.sock:/var/run/docker.sock
#    restart: unless-stopped





