name: Bricoll Docker Image Publish

on:
  push:
    branches: [ "Production" ]
    tags: [ "v*.*.*" ]
  pull_request:
    branches: [ "Production" ]
permissions:
  packages: write
  contents: read

env:
  # github.repository as <account>/<repo>
  IMAGE_NAME: bricoll

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2

      # https://github.com/docker/login-action
      - name: "Login via Azure CLI"
        uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}

      - name: "Build and push image"
        uses: azure/docker-login@v1
        with:
          login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}

      - run: |
          docker compose up --build -d
          docker tag mongo ${{ secrets.REGISTRY_LOGIN_SERVER }}/mongo:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/mongo:${{ github.sha }}
          docker tag redis ${{ secrets.REGISTRY_LOGIN_SERVER }}/redis:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/redis:${{ github.sha }}
          docker tag nextjs ${{ secrets.REGISTRY_LOGIN_SERVER }}/nextjs:${{ github.sha }}
          docker push ${{ secrets.REGISTRY_LOGIN_SERVER }}/nextjs:${{ github.sha }}



#
#      - name: "Deploy Mongo to Azure Container Instances"
#        uses: "azure/aci-deploy@v1"
#        with:
#          resource-group: ${{ secrets.RESOURCE_GROUP }}
#          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
#          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/mongo:${{ github.sha }}
#          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#          registry-username: ${{ secrets.REGISTRY_USERNAME }}
#          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
#          name: bricoll
#          location: "East US"
#      - name: "Deploy Redis to Azure Container Instances"
#        uses: "azure/aci-deploy@v1"
#        with:
#          resource-group: ${{ secrets.RESOURCE_GROUP }}
#          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
#          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/redis:${{ github.sha }}
#          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#          registry-username: ${{ secrets.REGISTRY_USERNAME }}
#          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
#          name: bricoll
#          location: "East US"
#      - name: "Deploy Nextjs to Azure Container Instances"
#        uses: "azure/aci-deploy@v1"
#        with:
#          resource-group: ${{ secrets.RESOURCE_GROUP }}
#          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
#          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/nextjs:${{ github.sha }}
#          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#          registry-username: ${{ secrets.REGISTRY_USERNAME }}
#          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
#          name: bricoll
#          location: "East US"
#      - name: "Deploy Nginx to Azure Container Instances"
#        uses: "azure/aci-deploy@v1"
#        with:
#          resource-group: ${{ secrets.RESOURCE_GROUP }}
#          dns-name-label: ${{ secrets.RESOURCE_GROUP }}${{ github.run_number }}
#          image: ${{ secrets.REGISTRY_LOGIN_SERVER }}/nginx:${{ github.sha }}
#          registry-login-server: ${{ secrets.REGISTRY_LOGIN_SERVER }}
#          registry-username: ${{ secrets.REGISTRY_USERNAME }}
#          registry-password: ${{ secrets.REGISTRY_PASSWORD }}
#          name: bricoll
#          location: "East US"
